/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserId = IDL.Principal;
export const PostId = IDL.Nat32;
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : PostId,
  'content' : IDL.Text,
  'authorId' : UserId,
  'bananaReactions' : IDL.Nat,
  'timestamp' : Time,
  'image' : IDL.Opt(IDL.Text),
});
export const User = IDL.Record({
  'id' : UserId,
  'username' : IDL.Text,
  'followersCount' : IDL.Nat,
  'avatarEmoji' : IDL.Text,
  'followingCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
  'createUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'reactToPost' : IDL.Func([PostId], [], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserId = IDL.Principal;
  const PostId = IDL.Nat32;
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : PostId,
    'content' : IDL.Text,
    'authorId' : UserId,
    'bananaReactions' : IDL.Nat,
    'timestamp' : Time,
    'image' : IDL.Opt(IDL.Text),
  });
  const User = IDL.Record({
    'id' : UserId,
    'username' : IDL.Text,
    'followersCount' : IDL.Nat,
    'avatarEmoji' : IDL.Text,
    'followingCount' : IDL.Nat,
  });
  
  return IDL.Service({
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(IDL.Text)], [], []),
    'createUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getPosts' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Post)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'reactToPost' : IDL.Func([PostId], [], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };